# Ejemplos


### 

GET http://localhost:3000/api/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/products/67ae4cbc85db8bb90621768b HTTP/1.1
content-type: application/json

{ 
    "_id": "67ae4cbc85db8bb90621768b",
    "marca": "prs",
    "precio": "3001",
    "foto": "https://res.cloudinary.com/meigemn/image/upload/v1739475950/61hcYYLWb3L._AC_SL1500__haqlei.jpg"
}

###
###Ya adaptado a jackson
DELETE http://localhost:3000/api/products/67ae4b4385db8bb906217686 HTTP/1.1 
content-type: application/json

###
###Ya adaptado a ibanez
DELETE https://nxapi-mongodb.vercel.app/api/products/67ae4c9a85db8bb90621768a HTTP/1.1
content-type: application/json

### 
### ya adaptado jackson
POST https://nxapi-mongodb.vercel.app/api/products HTTP/1.1
content-type: application/json

{ 
    "marca": "gibson", 
    "precio": 2000,
    "foto": "https://res.cloudinary.com/meigemn/image/upload/v1739477239/DSXE00CWCH1_front_dzaudo.png"
}

###  ya adaptado a jackson

DELETE https://nxapi-mongodb.vercel.app/api/products/67ae4b4385db8bb906217686
content-type: application/json
